### ISSUE TITLE
Replace all constante with upper case

### ISSUE THREAD

**Issue by The-CJ** [The-CJ/Phaazebot#47]

**Comment by andrewmsboyd** [comment]
Hey @The-CJ I'm a newbie looking for things to contribute to...would this be a good issue for me?

**Comment by The-CJ** [comment]
@andrewmsboyd mmm.. i don't really know,
first up my code is ... "special" and im not sure if you know what i use as a constante and what not.
u can try :D

**Comment by The-CJ** [comment]
@andrewmsboyd but wait a moment, i resync all of my changes first

**Comment by The-CJ** [comment]
if you want u can try now @andrewmsboyd , just fork the repo and work on the "osu" branch, there have the most resent changes
